env:
  es2020: true
  browser: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "react-hooks"
  - "emotion"
parserOptions:
  sourceType: module
settings:
  react:
    version: detect
rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - ignoreRestSiblings: true
      argsIgnorePattern: ^_
  react/prop-types: "off"
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  emotion/jsx-import: "error"
  emotion/no-vanilla: "error"
